# This is a basic workflow to help you get started with Actions

name: CI Test

on:
  push:
    branches: [ master ]

jobs:
  run-mvn-test:
    name: ${{ matrix.distribution }} ${{ matrix.version }} (jdk-x64) - ${{ matrix.os }} - Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        distribution: [ 'adopt', 'zulu' ]
        version: [ '11' ]
    steps:
      # Use preinstalled PostgreSQL
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      # Change user name and password to meet your requirements
      - name: Create additional user
        run: |
          sudo -u postgres psql --command="CREATE USER Tim PASSWORD 'Tim'" --command="\du"

      # Change database name to meet your requirements
      - name: Create additional database
        run: |
          sudo -u postgres createdb --owner=Tim account
          PGPASSWORD=foo psql --username=Tim --host=localhost --list timetable
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: ${{ matrix.distribution }}
      - name: Compile code
        run: mvn test
